### ISSUE TITLE
Enhancement: Hide the `value` row in Add Treasury Account Transaction

### ISSUE THREAD

**Issue by ipr0310** [signum-network/signum-explorer#100]
As the title says, the row ``value`` of a ``Add Treasury Account`` transaction in the transaction page.

In the transaction page, the value row must not be shown!
![image](https://user-images.githubusercontent.com/35440957/185749273-79a856f4-7973-4494-9211-a4ece4188068.png)

This is the URL of the transaction:
https://testnet.explorer.signum.network/tx/6849580233394516717

**Expected solution**
Hide ``value`` row

**Comment by pir8radio** [comment]
Add Treasury Account value will ALWAYS be zero?

**Comment by pir8radio** [comment]
i could not easily hide the whole row..    i can however make the table blank like we do everywhere else on the explorer..   https://explorer.notallmine.net/tx/12924546544212724141
