### ISSUE TITLE
Please use all 8 decimal places on the SIGNA numbers like the Classic Wallet?

### ISSUE THREAD

**Issue by paulpoco** [signum-network/signum-explorer#105]
Please use all 8 decimal places on the SIGNA numbers like the Classic Wallet?

Do not cut off at 5 decimal places as is being shown now.

**Comment by pir8radio** [comment]
@frankTheTank72 do you see any issues with this?   I am testing this on the account TX pages right now here: https://explorer.notallmine.net/txs/      probably leave 5 digit rounding on the home page.. just update on the tx pages..   thoughts?

**Comment by frankTheTank72** [comment]
I think we not touched that when we started the new explorer -maybe a display thingy ? If test are going well open for it

**Comment by pir8radio** [comment]
@frankTheTank72 can I maybe have ability to close issues?   Otherwise this one can be closed
