### ISSUE TITLE
Text messages in token transfer not shown.

### ISSUE THREAD

**Issue by deleterium** [signum-network/signum-explorer#106]
When getting the details if a transaction has token transfer, the message is not shown.

Example:

1) Transaction token transfer + message:

https://t-chain.signum.network/tx/192437928770573517
Transaction details (partial)
```
"transaction": "192437928770573517",
  "attachment": {
    "version.AssetTransfer": 1,
    "asset": "15297368334901195317",
    "version.Message": 1,
    "message": "Test Message",
    "messageIsText": true,
    "quantityQNT": "10"
  },
```

2) Transaction token transfer + signa + message:

https://t-chain.signum.network/tx/15036056002230554309
Transaction details (partial):
```
  "transaction": "15036056002230554309",
  "attachment": {
    "version.AssetTransfer": 1,
    "asset": "15297368334901195317",
    "version.Message": 1,
    "message": "trade",
    "messageIsText": true,
    "quantityQNT": "4562"
  },
```

Expected outcome: Text message is displayed in textarea

**Comment by deleterium** [comment]
Same on Alias Buy:

Example: [1831202506654360496](https://t-chain.signum.network/tx/1831202506654360496#)

**Comment by pir8radio** [comment]
this "should" be fixed, but i did not test with an alias.   can you test on main net and use https://explorer.notallmine.net and report back if it is now fixed?   I suspect it is now fixed with this PR: https://github.com/signum-network/signum-explorer/pull/122/commits/204c2584cd213f12eb0797d066547d7048acef1c

**Comment by deleterium** [comment]
Yes, fixed as https://explorer.notallmine.net/tx/13714710604617059866
