### ISSUE TITLE
Enhancement: show token id on multi-transfer

### ISSUE THREAD

**Issue by deleterium** [signum-network/signum-explorer#110]
Currently it is not possible to go to assets in **asset multi transfer**.

Example: https://t-chain.signum.network/tx/2808521283373730884

It is expected that there is some information about the tokens (token id or link to the token) in the page, so user can get more details of that token. Showing only the name does not help, because there is no search by token name and there could be many tokens with same name.

**Comment by frankTheTank72** [comment]
fixed

https://t-chain.signum.network/tx/2808521283373730884
