### ISSUE TITLE
Text message in Subscription Subscribe transaction is not shown

### ISSUE THREAD

**Issue by ipr0310** [signum-network/signum-explorer#120]
When getting the details of a `Subscription Subscribe` transaction,  the message is not shown.
![image](https://user-images.githubusercontent.com/35440957/202083221-25890853-374c-4908-93cf-f8c0052c4060.png)

Link of transaction:
https://testnet.explorer.signum.network/tx/4414824258562080750

You can see in api, message is shown, but not on explorer:
https://europe3.testnet.signum.network/api?requestType=getTransaction&transaction=4414824258562080750
```json
{
  "attachment": {
    "version.SubscriptionSubscribe": 1,
    "frequency": 3600,
    "version.Message": 1,
    "message": "{\"message\":\"hello world!\"}",
    "messageIsText": true
  },
}
```

**Comment by pir8radio** [comment]
also not shown to contracts   https://t-chain.signum.network/tx/4792805042978716225

**Comment by pir8radio** [comment]
Fixed in this PR: https://github.com/signum-network/signum-explorer/pull/122/commits/204c2584cd213f12eb0797d066547d7048acef1c      here is a subscription with message: https://explorer.notallmine.net/tx/15380928695827209893
