### ISSUE TITLE
Enhancement: Token Transfers transactions list must show Token Ticker

### ISSUE THREAD

**Issue by ipr0310** [signum-network/signum-explorer#134]
Once you are watching the token transfer of any account in the explorer, you can see the ticker and token ID on ``Token Transfers``
![image](https://user-images.githubusercontent.com/35440957/218637583-79d33c33-bbe4-4d21-96c6-f5e18365f3cc.png)

But once you click into ``View all transfers``
![image](https://user-images.githubusercontent.com/35440957/218637622-1c3d3642-6d30-482b-a559-7ce4c53c093e.png)

The token ticker and id is not being shown
![image](https://user-images.githubusercontent.com/35440957/218637665-eaf9c417-866a-4fdd-9f30-2f025075d5c1.png)
https://explorer.signum.network/asset/transfers?a=11224962117215913721

**Comment by frankTheTank72** [comment]
Fixed on testnet
https://t-chain.signum.network/address/1201132855700520531

Will be deployed with next node update (3.6.1)
