### ISSUE TITLE
Long Loading Times for initial page

### ISSUE THREAD

**Issue by ohager** [signum-network/signum-explorer#135]
I perceive massive loading times 15+ (fifteen!) seconds until the home page is being rendered...
This should - iff possible - be improved. 

Because of the long loading times I even checked my internet connection, just to see that it's not on my side. ;)

**Comment by gittrekt** [comment]
> I perceive massive loading times 15+ (fifteen!) seconds until the home page is being rendered...
> This should - iff possible - be improved. 
> 
> Because of the long loading times I even checked my internet connection, just to see that it's not on my side. ;)

Have you tried adding these to your database these entries? It should be added to the node database. 

CREATE INDEX transaction_height_timestamp ON transaction(height, timestamp);

CREATE INDEX asset_height ON asset(height);

**Comment by frankTheTank72** [comment]
> > I perceive massive loading times 15+ (fifteen!) seconds until the home page is being rendered...
> > This should - iff possible - be improved.
> > Because of the long loading times I even checked my internet connection, just to see that it's not on my side. ;)
> 
> Have you tried adding these to your database these entries? It should be added to the node database.
> 
> CREATE INDEX transaction_height_timestamp ON transaction(height, timestamp);
> 
> CREATE INDEX asset_height ON asset(height);

Yes both indicies already exists on the DB

**Comment by frankTheTank72** [comment]
@pir8radio do you have also something those long loading times ? 
On https://chain.signum.network/ sometimes loading is slow - but most of the time it is super fast

**Comment by pir8radio** [comment]
> 

i do on my testnet but not my mainnet.     both are ubuntu VM's  Both use networked maria DB's (db server is its own server not local)  both basically have unlimited ram (cache)  so im not sure why one sees this issue and one does not.  We probably need to dig deeper.

**Comment by pir8radio** [comment]
This should be fixed in this pr: https://github.com/signum-network/signum-explorer/pull/136
pre-cache the total supply query.   it was counting every wallet then summing the wallet total and ignoring the burn account, to come up with the total supply..   This now runs as a timed task so users do not see a delay.

**Comment by ohager** [comment]
yeah, checked it.... loading time is somewhere between 1 and 3 secs.... can be latency here. Good Job
