### ISSUE TITLE
[Feature Request]  in Distributions add the name of the "To" in addition to the regular address

### ISSUE THREAD

**Issue by paulpoco** [signum-network/signum-explorer#141]
[Feature Request]  in Distributions add the name of the "To" in addition to the regular address.   It seems to do the "From" name just fine.

![image](https://user-images.githubusercontent.com/801414/230729447-3d013802-5d3e-4dd6-a300-1f0ba18645ce.png)

**Comment by pir8radio** [comment]
someone must have fixed this already and didnt close out this issue..   i just tested looks like it works..

![image](https://github.com/signum-network/signum-explorer/assets/16748696/90d3a790-c7aa-4c97-9996-b4e9f0496aa5)
