### ISSUE TITLE
Enhancement: Show details of multi-asset transactions

### ISSUE THREAD

**Issue by ipr0310** [signum-network/signum-explorer#147]
On the following transaction, i sent `51 TSIGNA` and `0.7829 PREAS`

The error is that the explorer only shows the `PREAS` sent, not the amount of `SIGNA` sent
It must show multiple assets, not only 1

![image](https://github.com/signum-network/signum-explorer/assets/35440957/000eebee-23fe-431c-8d19-4921c4adb649)

Transaction Link: https://t-chain.signum.network/tx/5072084061849514585

**Comment by ipr0310** [comment]
You can check the amountNQT on the api call: https://europe3.testnet.signum.network/api?requestType=getTransaction&transaction=5072084061849514585

```json
{
  "type": 2,
  "subtype": 1,
  "timestamp": 284070084,
  "deadline": 1440,
  "senderPublicKey": "7158e2e1170f9a3e1799ba4069ab55fac3d2242db5c0a08faf91c8b7cac3cb1f",
  "recipient": "5798204493884368473",
  "recipientRS": "TS-UBLT-AKEJ-F5KZ-7WUX2",
  "amountNQT": "5100000000",
  "feeNQT": "1000000",
  "referencedTransactionFullHash": "e4d02890d72130a5ada643367a14aa95901907cf9ce3081ff02f3d23d8562fd3",
  "signature": "948cfbde2ce441e2195676d135d4f5a759415fb5df97ab4e8df81df3a2e5770bef5055cf935d25c562e5b43894bc4b2cadb0e720db7213baa105b8f76eefada5",
  "signatureHash": "787a1d044f671c26f49729de223f59a2d2e08519b02b1936545cde967e261c11",
  "fullHash": "59f275c994a9634627a8e7ad18046aa953be38738a98953c11f1a00f5e1c0ab9",
  "transaction": "5072084061849514585",
  "attachment": {
    "version.AssetTransfer": 1,
    "asset": "13173437187473628239",
    "version.Message": 1,
    "message": "0100000000000000",
    "messageIsText": false,
    "quantityQNT": "7829"
  },
  "attachmentBytes": "014f5c497e5373d1b6951e00000000000001080000000100000000000000",
  "sender": "8629824288351884182",
  "senderRS": "TS-36WQ-GYQN-D856-9DUJH",
  "height": 577983,
  "version": 2,
  "ecBlockId": "4455825082731645138",
  "ecBlockHeight": 577972,
  "cashBackId": "8952122635653861124",
  "block": "12919220632867849742",
  "confirmations": 0,
  "blockTimestamp": 284070286,
  "requestProcessingTime": 3
}
```

**Comment by pir8radio** [comment]
like this?   https://t-explorer.notallmine.net/tx/5072084061849514585

Please test with another tx where you send no signa..    also send with multiple assets?  please let me know how it responds. 


NOTE TO SELF:
changed scan/templates/txs/detail.html
added line 125 & 126 in testnet explorer, removed <br> from token symbol, looked strange on a new line.

**Comment by frankTheTank72** [comment]
Yes you can send Signa with a token transfer - signa and up to 4 tokens are possible
