### ISSUE TITLE
Enhancement: Support line breaks on token page description

### ISSUE THREAD

**Issue by ipr0310** [signum-network/signum-explorer#163]
As the title says, when i'm looking a token details, the line-breaks seems to be not supported
![image](https://github.com/signum-network/signum-explorer/assets/35440957/54967855-0baa-44e4-90d9-80f24fa29c77)

**Comment by ipr0310** [comment]
Example of description with line-breaks being read on SignumSwap
![image](https://github.com/signum-network/signum-explorer/assets/35440957/d3161339-7323-427d-9c08-75ffa2e5ca6a)

**Comment by pir8radio** [comment]
Line breaks are pre-formatted based on data.   

Name
Description (word wrap auto break) 

It's purposely not allowed otherwise you can load the description up with line breaks and create a large white space.  Pushing data out of view.   We force some formatting.
