### ISSUE TITLE
Top accounts page has timeouts frequently

### ISSUE THREAD

**Issue by MrSon1Q** [signum-network/signum-explorer#182]
When I try to see top accounts in explorer I get time outs frequently. 
<img width="1858" alt="image" src="https://github.com/signum-network/signum-explorer/assets/22246176/e5285c38-fbbd-43c1-b39d-362d02e795dc">

I guess that it can be fixed by some approaches:

1. Add a new index for the balance column in the account balance table. (The column is updated frequently, maybe that's why you haven't added it yet)

2. The current logic retrieves the top 1000 records from the database, and then filters them to the page value (25) only to prevent the possibility of generating queries for the top 1000+. I think that we can consider other ways to prevent the user from accessing the Nth page that generates such queries and always get the top 25 records, instead of 1000.

**Comment by pir8radio** [comment]
are you seeing this on both explorers?     https://explorer.notallmine.net

**Comment by pir8radio** [comment]
fixed in PR: https://github.com/signum-network/signum-explorer/pull/184
