### ISSUE TITLE
Processing Error

### ISSUE THREAD

**Issue by arnemetis** [signum-network/signum-explorer#183]
Error while processing, URL: https://chain.signum.network/target=

**Comment by pir8radio** [comment]
/target=  i would expect you get a 404 error.  What were you expecting?

**Comment by arnemetis** [comment]
I was getting an error 500 Processing Error for the last day or two. I checked now and it's working again.

**Comment by pir8radio** [comment]
There are multiple explorers.    Https://explorer.notallmine.net is another
one I run.    All should be linked from the main signum.network site too.
