### ISSUE TITLE
[Feature Request] - Show Pool account mined blocks like Existing Explorer

### ISSUE THREAD

**Issue by paulpoco** [signum-network/signum-explorer#32]
[Feature Request] - Show Pool account mined blocks like Existing Explorer

Existing Explorer
![Existing Explorer](https://user-images.githubusercontent.com/801414/146656349-0e4ab1e2-c9be-4b35-b500-dcf8bda768ed.png)

New chain Explorer
![New Explorer](https://user-images.githubusercontent.com/801414/146656360-d7316727-6cc8-4c55-9051-d66f12ed3592.png)

**Comment by jjos2372** [comment]
Thanks for the request. That information is not directly available on nodes, individual miners are stored as the "block forgers" and not the pool. A separate treatment needs to be specially implemented, tracking the pool of every forged blocks and storing that information (recalling miners can switch pools over time). For now there are other websites for tracking mining pools.

**Comment by paulpoco** [comment]
Wonder the existing Explorer does that?

**Comment by jjos2372** [comment]
> Wonder how the existing Explorer does that?

Yes, they do something with a new table or similar. So, sometimes you see discussions about which pool actually got a block because they can get it wrong with short lived forks if you don't handle that carefully.

**Comment by pir8radio** [comment]
That's something else missing...    on the pool wallet page,  a list of people who have set their "reward recipient" to that wallet..  Node API "getAccountsWithRewardRecipient"  If that list existed you could scan the list of miners assigned to that pool for their last blocks and display the pool won blocks that way?    prob not super efficient....

**Comment by jjos2372** [comment]
> That's something else missing... on the pool wallet page, a tab/list of people who have set their "reward recipient" to that wallet.. Node API "getAccountsWithRewardRecipient" If that list existed you could scan the list of miners assigned to that pool for their last blocks and display the pool won blocks that way? prob not super efficient....
> 
> Probably should add the tab for accounts with reward recipient to the wallet page though..

That would give you only the "latest" pool the account joined, so it would not be reliable. You need to actually iterate over all blocks and build this information if you want.

**Comment by pir8radio** [comment]
> 

I just want the list of who has their reward recipient set to the account you are viewing..   much like if i were to look at my pool account on explorer i would expect the tab for pool members to display this info:  https://signawallet.notallmine.net/burst?requestType=getAccountsWithRewardRecipient&account=S-S456-G8QD-HZQ7-B66VL

**Comment by rodrigue10** [comment]
> > That's something else missing... on the pool wallet page, a tab/list of people who have set their "reward recipient" to that wallet.. Node API "getAccountsWithRewardRecipient" If that list existed you could scan the list of miners assigned to that pool for their last blocks and display the pool won blocks that way? prob not super efficient....
> > Probably should add the tab for accounts with reward recipient to the wallet page though..
> 
> That would give you only the "latest" pool the account joined, so it would not be reliable. You need to actually iterate over all blocks and build this information if you want.

I was playing around with this concept for a while and if you're looking to reconstruct the  "Pool who won the block"  this DB query should build all this information for you.  Does a cross reference of the `block` with the `transaction` table for a `Reward Recip` transaction type. 
It is not something that could likely be used "on the fly" for a web-page given the subquery used to make it but it could be a starting point for a procedure/lookup query for building a secondary table.  Something to play with if you decide to start including this for a pool's details.

```sql 
SELECT sl.height, sl.generator_id, IFNULL(sl.pool,sl.generator_id) as pool from (
	SELECT
		b.height ,
		b.generator_id,
		(select t.recipient_id from `transaction` t WHERE t.`type` = 20 and t.subtype = 0 and t.sender_id = b.generator_id and (t.height + 4) <= b.height order by t.height DESC limit 1) pool from block b 
) sl
```

**Comment by Zoh63392187** [comment]
That information was gathered and put together in a new table due to performance.

Also @rodrigue10  that query needs to be done in another way as performance would be really poor due to your injected selects.

**Comment by rodrigue10** [comment]
@Zoh63392187 , 
Yes, as i stated, the query i posted should not be used "on demand" , but rather used in some sort of service that builds the desired lookup table.

**Comment by pir8radio** [comment]
feature added with https://github.com/signum-network/signum-explorer/pull/158
