### ISSUE TITLE
Signum Nodes Distribution page has empty content

### ISSUE THREAD

**Issue by ipr0310** [signum-network/signum-explorer#36]
![explorer signum network_peers-charts_](https://user-images.githubusercontent.com/35440957/146788660-6cba8f20-0b1b-4db8-b604-85c95cf14897.png)

As you can see in the image:
- The map details are empty
- "No data" in the node versions
- Only "All known peers" appears

**Comment by jjos2372** [comment]
The node detection logic was reworked, it looks like it is working now. Please re-open if the problem persists.
