### ISSUE TITLE
All accounts without reward assignment are 'Solo Miner' 

### ISSUE THREAD

**Issue by erdnapa** [signum-network/signum-explorer#50]
The explorer treats non-mining accounts as 'Solo Miner', even if the accounts have 0 block wins and no reward assignment.
An better option wold be 'Pool: none' in such cases.

For instance: [TRT](https://explorer.signum.network/address/3987922920963855008) has Pool: Solo Miner

**Comment by pir8radio** [comment]
yea right now its assumed that if the address is not assigned to a pool, they could solo mine.     So though they may not be mining at all, they still could be a solo miner.        the explorer has no way of knowing that user will never solo mine.   but it does know if reward assignment is assigned to a pool...
