### ISSUE TITLE
Pendent transaction does not appear in "search"

### ISSUE THREAD

**Issue by ipr0310** [signum-network/signum-explorer#54]
I was searching a pendent transaction with the "search box"
Why on the search box when i tried to search a "pendent transaction" by its id. is not found?
But that transaction is already available accessing directly with the URL, does it happens because the transaction is on mempool?

![image](https://user-images.githubusercontent.com/35440957/150774091-180c7fa4-df2e-42e6-8bf6-442e06b9d9b3.png)

https://testnet.explorer.signum.network/search/?q=18322294500440990763&submit=Search

![image](https://user-images.githubusercontent.com/35440957/150774145-faaf1410-8c59-4aa7-bdca-06638e08796d.png)
![image](https://user-images.githubusercontent.com/35440957/150774175-051bacb5-d629-4b81-934c-99ed8b61844e.png)

It appears when the tx has "0 or greater" Block confirmations
![image](https://user-images.githubusercontent.com/35440957/150774208-4c55490d-0d58-4186-91d2-67a3634d1e41.png)

**Comment by pir8radio** [comment]
Yes.  If Pending are not fully in the db at time of search it will not find.    I know no easy way around this.

**Comment by pir8radio** [comment]
@frankTheTank72 can close this one i think.
