### ISSUE TITLE
Glitches on smart contracts messages

### ISSUE THREAD

**Issue by deleterium** [signum-network/signum-explorer#56]
Problem:
The decoded text for smart contract messages present glitches.

Expected outcome:
Decoded text working similar to previous block explorer, where invalid bytes were not shown.

Examples:
* Null bytes at the end not removed: https://testnet.explorer.signum.network/tx/7265143136323086885
Presented: **Transaction processed.����������**
Expected: **Transaction processed.**

* Invalid utf-8 bytes: https://testnet.explorer.signum.network/tx/14352747426541831797
Presented:
Expected: **9**

**Comment by rogerwim** [comment]
also https://explorer.signum.network/at/10329395115840040763, thats a at with null bytes as description, it is also impoperly filterd

**Comment by pir8radio** [comment]
are the null bytes (unicode) in the blockchain TX if you get transaction from a node?   django supports unicode an will send whatever is in the true blockchain field.   if these unicode null bytes exist in the real code they will be shown..    Just curious why the smart contract is including a bunch of null bytes?

**Comment by deleterium** [comment]
The problem is that the smart contract can attach or not a message. But if a message is attached, it is not possible to control the length. Sending just a long (first 8 bytes) and the node will fill the remaining data with zeros.

Previous software supports these messages, stripping the invalid/null bytes from messages:
* Classic wallet
* Phoenix wallet
* Previous block explorer from Zoh

So if I develop a contract now, I will need to set all remaining chars to space/blank. But this will break backwards compatibility with contracts and messages already on chain.

**Comment by deleterium** [comment]
My opinion about this issue:
Strip invalid bytes and show "dirty data" from random bytes can be disabled, I would not mind about that because the bytes does not represent a utf-8 data. But I expect that a valid utf-8 is printed until first zero byte, that is the commom representation of strings (ending with a null). Some examples:
TextData\0\0\0\0  -> 'TextData'
TextData\0randombytes -> 'TextData'
randombytes -> ''
randombyte\0TextData -> ''

But, for the compatibility, I would just strip invalid utf-8 data and show dirty bytes:
TextData\0\0\0\0  -> 'TextData'
TextData\0randombytes ->  'TextData?çì$'
randombytes -> 'zâ=ẁ!'
randombyte\0TextData -> 'çṕà%sTextData'

**Comment by pir8radio** [comment]
You may be correct I’m just talking through this.    Have you tested Unicode and other languages?   I say fix it on the input side.   I’m a little confused how people are putting in stuff then confused it’s coming back out.  😊 I put this turd in a box, close it, open the box an hour later, it shouldn’t be a surprise to me that there is a turd inside.  😂.  I’m game for anything.  Want to make sure we don’t strip chars that others will use in the future, to make something act how it has in the past.   What goes in should come out.      Fix what goes in.   IMO.   May not be right though. 😀

**Comment by deleterium** [comment]
Just to be clear that invalid utf-8 bytes are different from characters with code over 127 (non-ASCII). There is an algorithm to encode the unicode text into bytes, and I mean invalid utf-8 when this sequence does not conform with the algorithm. https://en.wikipedia.org/wiki/UTF-8

**Comment by pir8radio** [comment]
> Problem: The decoded text for smart contract messages present glitches.
> 
> Expected outcome: Decoded text working similar to previous block explorer, where invalid bytes were not shown.
> 
> Examples:
> 
> * Null bytes at the end not removed: https://testnet.explorer.signum.network/tx/7265143136323086885
>   Presented: **Transaction processed.����������**
>   Expected: **Transaction processed.**
> * Invalid utf-8 bytes: https://testnet.explorer.signum.network/tx/14352747426541831797
>   Presented:
>   Expected: **9**

Do you have a production explorer example so i can troubleshoot this?

**Comment by pir8radio** [comment]
> > Problem: The decoded text for smart contract messages present glitches.
> > Expected outcome: Decoded text working similar to previous block explorer, where invalid bytes were not shown.
> > Examples:
> > 
> > * Null bytes at the end not removed: https://testnet.explorer.signum.network/tx/7265143136323086885
> >   Presented: **Transaction processed.����������**
> >   Expected: **Transaction processed.**
> > * Invalid utf-8 bytes: https://testnet.explorer.signum.network/tx/14352747426541831797
> >   Presented:
> >   Expected: **9**
> 
> Do you have a production explorer example so i can troubleshoot this?

can you do similar test now on main net and use https://explorer.notallmine.net to test?     I do not limit this view to UTF-8 but we can if we find a need...    Is there any reason not to limit this field to UTF-8?   will it limit Chinese characters or any other language?

**Comment by Zoh63392187** [comment]
I remember this from back in the days and a really pain so solve. 

- First I inspected the message to see if a "has_public_key_announcement" if it did not I grabbed the first 5 bytes.

```
$str = substr($message['attachment_bytes'], 5);
if($message['has_public_key_announcement']=='1') $str = substr($str, 0, -33);
```

- Converted/encoded the message to utf8/ISO-8859-1
- Removed invalid charaters
- Posted the message

I hope it helps :)

**Comment by pir8radio** [comment]
Closing this ticket, its on my short term to-do list here: 179
