### ISSUE TITLE
smart contract can have null bytes in desciption

### ISSUE THREAD

**Issue by rogerwim** [signum-network/signum-explorer#58]
see https://explorer.signum.network/at/10329395115840040763, there are null bytes there that are improperly filtered, i would not expect that to happen

**Comment by pir8radio** [comment]
I recall looking into this.   Did we ever take care of this one roger?

**Comment by pir8radio** [comment]
Oh.  This issue should be merged with this one. 

https://github.com/signum-network/signum-explorer/issues/56
