### ISSUE TITLE
Pending Tx cannot be addressed - getting Error 500

### ISSUE THREAD

**Issue by ohager** [signum-network/signum-explorer#61]
Steps to reproduce:

- Having a transaction in the pending section
- Click on the link of the Tx ID
- Getting Error 500

Expected Behavior:
At least show some basic information, and not an error page

Once the Tx is not pending anymore all works as expected

![image](https://user-images.githubusercontent.com/3920663/153727406-87f7c1f7-1b62-4f43-bd64-53e8bb125aa2.png)

**Comment by jjos2372** [comment]
Maybe this was a temporary glitch or some special transaction type?

Because if we go to https://explorer.signum.network/txsPending/ and select a random pending tx it shows the details with the height *pending*:
![image](https://user-images.githubusercontent.com/31958515/153727953-2cdc9bfb-2532-4ccf-b572-524d0e9c1211.png)

**Comment by pir8radio** [comment]
I have seen this on NEW WALLETS..  going through the activation process.  Can someone confirm its just new wallets, or specific tx types?

**Comment by jjos2372** [comment]
> I have seen this on NEW WALLETS.. going through the activation process. Can someone confirm its just new wallets, or specific tx types? as soon as block is confirmed the link then works..

I guess you mean new accounts.

**Comment by pir8radio** [comment]
yes, i fixed my comment....  :-)

**Comment by jjos2372** [comment]
ok, on it.

**Comment by jjos2372** [comment]
Just tested and not an issue on testnet with account activation.

**Comment by pir8radio** [comment]
I did not get a 500 this time,   i got a 404 which i would expect for an account that doesn't have a public key or account balance yet..      
![image](https://user-images.githubusercontent.com/16748696/153729442-22565d27-a819-4f7d-bf4e-d94978a493a2.png)

**Comment by pir8radio** [comment]
Tested with "Token Transfer" as that was the TX type OP saw the 500 error on...  I think this may be related to specific accounts, another bug..   Looking into now..   
![image](https://user-images.githubusercontent.com/16748696/153730742-594cbb3e-d59b-4aec-aedb-3ef893364c4b.png)

**Comment by rogerwim** [comment]
> Tested with "Token Transfer" as that was the TX type OP saw the 500 error on...  I think this may be related to specific accounts, another bug..   Looking into now..   
> 
> ![image](https://user-images.githubusercontent.com/16748696/153730742-594cbb3e-d59b-4aec-aedb-3ef893364c4b.png)
> 
> 
> 
> 

S-RRA3-QSMU-5T3L-ACY49-1CWZGYTP3DU5I08EUFYEHOWPV9SU11XD19H28EJLL6U4HU7BS8
This was the involved recipient
