### ISSUE TITLE
Feature Request:  On main page of an address, make cashback total clickable to open to a page that shows cashback for each month in the last 12 months.

### ISSUE THREAD

**Issue by paulpoco** [signum-network/signum-explorer#68]
Feature Request:  On main page of an address, make cashback total clickable to open to a page that shows cashback for each month in the last 12 months.
Here
![image](https://user-images.githubusercontent.com/801414/159519477-5c62086f-551a-41b0-8831-c2757c9dd4d6.png)

**Comment by pir8radio** [comment]
There is already a direct link to cashbacks on that same page.  Is that not what you were looking for?   Would be a one off if we added a special link for this one function, and not links for all the others, which could look messy?   thoughts?

![image](https://user-images.githubusercontent.com/16748696/159585352-11915b35-cee0-4200-9747-060bab0800a0.png)

**Comment by pir8radio** [comment]
how about a CSV export for cashbacks like in transactions, then you can do whatever you want with it?
