### ISSUE TITLE
[Feature Request] Upgrade status for text messages

### ISSUE THREAD

**Issue by deleterium** [signum-network/signum-explorer#70]
Messages can be transmitted in the blockchain. It is a powerful feature of Signum.

I think this is a important information that must be showed directly as show.

![image](https://user-images.githubusercontent.com/54009773/163080646-882b20b7-1a9a-4c85-b1bb-dbbe20c9312d.png)

If the text is empty, it can be omitted or showed only in the detailed information.

**Comment by pir8radio** [comment]
It is shown.  You mean without clicking "toggle details"?

**Comment by deleterium** [comment]
@pir8radio Yes. I think the message is much important to user. The other details like deadline, has message, full hash are more to devs and are Ok to be hidden during page load.

**Comment by pir8radio** [comment]
Test here, if you like ill add to my open pull request.   https://explorer.notallmine.net

**Comment by pir8radio** [comment]
I cant close these, so you can if you like deleterium.   should be included in current build after they update on the servers.
