### ISSUE TITLE
Provide contract links for running contracts in a block

### ISSUE THREAD

**Issue by jjos2372** [signum-network/signum-explorer#72]
Instead of the byte array of contracts running in a block, show a list with the contract links.

**Comment by pir8radio** [comment]
3EBA832D8F2C82FE86B69262CC1A4F50E0CF4BBFC9FFEF4D        what does this even represent?  how do i convert?

**Comment by jjos2372** [comment]
You have to break it for the ID of each contract, it should be like this:
```
3EBA832D8F2C
82FE86B69262
CC1A4F50E0CF
4BBFC9FFEF4D
```
And then convert each one to the integer (long, unsigned).

**Comment by pir8radio** [comment]
to what type of unsigned int  I have tried converting it to 8, 32,16, 64 bit and none of them come out to a valid contract ID...

**Comment by jjos2372** [comment]
It is a 64 bit int, little endian format.

**Comment by pir8radio** [comment]
> 3EBA832D8F2C

yea first one doesnt come back to a valid contract...

![image](https://user-images.githubusercontent.com/16748696/204095625-8da058d5-ef0b-44a1-bb3b-11de29b26ac6.png)

**Comment by jjos2372** [comment]
Sorry, I broke it wrong, `3EBA832D8F2C82FE86B69262CC1A4F50E0CF4BBFC9FFEF4D` should be:
```
3EBA832D8F2C82FE
86B69262CC1A4F50
E0CF4BBFC9FFEF4D
```

Where the first one is the AT id running and the following 2 are the MD5 check for the contract contents (you can ignore).  So they always come this way, one ID and two other long values you skip.

You can check the conversion with http://localhost:8125/burst?requestType=getATLong&hexString=3EBA832D8F2C82FE
this should return:
`{"hex2long":"18339269626061634110","requestProcessingTime":0}`

Then you can get the contract details with http://localhost:8125/burst?requestType=getAT&at=18339269626061634110

Of course this is just for testing, you would do it directly in Python code.

**Comment by pir8radio** [comment]
one more question, what would it look like if that block had two or three contracts running?

**Comment by pir8radio** [comment]
never mind, i see its just a really long string...    oof this could get hard with more than one contract lol..   i know how to convert the hex little endian to dec....  but need to figure out how to handle   first 16, skip 32, next 16 skip32  etc... 

Dim h = "3EBA832D8F2C82FE"
If h.Length Mod 2 = 1 Then h = "0" & h
Dim r = ""
For i = 0 To h.Length - 1 Step 2
    r = h.Substring(i, 2) & r
Next
Dim a = Convert.ToInt64(r, 16)
Console.WriteLine(a) ' outputs 18339269626061634110

**Comment by pir8radio** [comment]
just... posting this here so i dont forget about it..      

 from binascii import a2b_hex
 import struct

 s = '2692692A7BAE0E47430678A4B4382D13F032AE1C509ED523EF747FF795260E917A0DA53F07140C408DA814235B0A2BDD3EBA832D8F2C82FE0AD1B0FD092515A475C04BC130D77E3C'
 
 for x in (s[k:k+16] for k in range(0, len(s), 3*16)):
     z = a2b_hex(x)
     i = struct.unpack('<Q', z)[0]
      print(x, i)
 __________________________________________________________________________________________
2692692A7BAE0E47 5120221670382604838
EF747FF795260E91 10452334210717807855
3EBA832D8F2C82FE 18339269626061634110`

**Comment by pir8radio** [comment]
Hard part is done,     https://explorer.notallmine.net/block/1084899

**Comment by pir8radio** [comment]
@frankTheTank72  you can close this as complete..  though i need to find a more elegant way of doing this rather than javascript, it seems the data is rendered and filtered, trying to then add data in the template stage doesnt work..   this might have to be a whole new queryset to get the correct data to show..    but javascript works well now..  even if javascript is broken still works as expected just no clickable links. 

https://github.com/signum-network/signum-explorer/pull/122/commits/72639e70651eadf53772ac83131c781f27b2be27
