### ISSUE TITLE
Feature Request: Add search line inside an address

### ISSUE THREAD

**Issue by rever273** [signum-network/signum-explorer#75]
An example: User want to know when he transferred coins to a certain wallet, he do not remember the date, but know the full address of the wallet. Can you add a search line within all transactions of the specified wallet, to find the right ones?

![image](https://user-images.githubusercontent.com/77928665/169032743-17a8c2de-aaf8-49d7-b3a3-5da3213e5519.png)

User can find: Address, amount of coins or transaction type

**Comment by pir8radio** [comment]
didnt forget about this,  really want to improve search, and column filtering in explorer.   hope to have time this winter to really re-do this.

**Comment by pir8radio** [comment]
added new tx filter option, you can now search and filter and restrict results to one address.  added in this pr: https://github.com/signum-network/signum-explorer/pull/178
