### ISSUE TITLE
Enhancement: Transactions list of the transaction type "Distribute to Holders" should be sorted by value

### ISSUE THREAD

**Issue by ipr0310** [signum-network/signum-explorer#87]
As you can see in the following link:
https://chain.signum.network/distribution/?a=16359283206797331913

This is the initial list, which seems to sort the transaction by value, ``Low to High``
![image](https://user-images.githubusercontent.com/35440957/176767818-837cabc3-fcd6-41f4-b1f3-2ab9f891a67d.png)

This is the Transaction ID:
https://chain.signum.network/tx/16359283206797331913

**Describe the solution you'd like**
The transactions should be sorted by its value``(From High to Low)``

**Comment by paulpoco** [comment]
Yes sort from high to low
